foreground           #e6e9ef
background           #0f1115
selection_foreground #aab1bf
selection_background #1a1f29
url_color            #7aa2f7
cursor               #e6e9ef
cursor_text_color    #151821

# normal
color0  #0f1115
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #73daca
color7  #aab1bf

# bright
color8  #2a3140
color9  #ff9e9e
color10 #b9f27c
color11 #fce094
color12 #a3c4f3
color13 #d4b6f4
color14 #9be0d2
color15 #e6e9ef
