layerrule = no_anim on, match:namespace zen0x-launcher
layerrule = blur on, match:namespace zen0x-launcher
layerrule = ignore_alpha 0.3, match:namespace zen0x-launcher

layerrule = blur on, match:namespace zen0x-bar
layerrule = ignore_alpha 0.3, match:namespace zen0x-bar

layerrule = blur on, match:namespace zen0x-powermenu
layerrule = ignore_alpha 0.3, match:namespace zen0x-powermenu
