workspace = 1, persistent:true, layoutopt:direction:right
workspace = 2, persistent:true, layoutopt:direction:down
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
