pragma Singleton
import QtQuick

// Generated by zen0x theme engine — edit zen0x/templates/quickshell-colors.qml.tpl
QtObject {
    readonly property color surface:                   "{{ bg0 }}"
    readonly property color surfaceDim:                "{{ bg0 }}"
    readonly property color surfaceBright:             "{{ bg2 }}"
    readonly property color surfaceContainerLowest:    "{{ bg0 }}"
    readonly property color surfaceContainerLow:       "{{ bg1 }}"
    readonly property color surfaceContainer:          "{{ bg1 }}"
    readonly property color surfaceContainerHigh:      "{{ bg2 }}"
    readonly property color surfaceContainerHighest:   "{{ bg3 }}"

    readonly property color contentSurface:            "{{ fg0 }}"
    readonly property color contentSurfaceVariant:     "{{ fg1 }}"
    readonly property color inverseSurface:            "{{ fg0 }}"
    readonly property color inverseContentSurface:     "{{ bg1 }}"

    readonly property color primary:                   "{{ accent }}"
    readonly property color contentPrimary:            "{{ bg0 }}"
    readonly property color primaryContainer:          "{{ bg2 }}"
    readonly property color contentPrimaryContainer:   "{{ fg0 }}"
    readonly property color inversePrimary:            "{{ accent }}"

    readonly property color secondary:                 "{{ cyan }}"
    readonly property color contentSecondary:          "{{ bg0 }}"
    readonly property color secondaryContainer:        "{{ bg2 }}"
    readonly property color contentSecondaryContainer: "{{ fg0 }}"

    readonly property color tertiary:                  "{{ yellow }}"
    readonly property color contentTertiary:           "{{ bg0 }}"
    readonly property color tertiaryContainer:         "{{ bg2 }}"
    readonly property color contentTertiaryContainer:  "{{ fg0 }}"

    readonly property color error:                     "{{ red }}"
    readonly property color contentError:              "{{ bg0 }}"
    readonly property color errorContainer:            "{{ bg2 }}"
    readonly property color contentErrorContainer:     "{{ fg0 }}"

    readonly property color outline:                   "{{ bg4 }}"
    readonly property color outlineVariant:            "{{ bg3 }}"

    readonly property color shadow:                    "#000000"
    readonly property color scrim:                     "#000000"
}
