#################
### AUTOSTART ###
#################

exec-once = uwsm app -- ags run --gtk 4 /home/aman/dotfiles/ags/app.ts
exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- openrgb -p red
exec-once = uwsm app -- gpu-screen-recorder

# Clipboard history daemon
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

