pragma Singleton
import QtQuick

// Generated by zen0x theme engine — edit zen0x/templates/quickshell-colors.qml.tpl
QtObject {
    readonly property color surface:                   "#0f1419"
    readonly property color surfaceDim:                "#0f1419"
    readonly property color surfaceBright:             "#30363d"
    readonly property color surfaceContainerLowest:    "#0f1419"
    readonly property color surfaceContainerLow:       "#161b22"
    readonly property color surfaceContainer:          "#161b22"
    readonly property color surfaceContainerHigh:      "#30363d"
    readonly property color surfaceContainerHighest:   "#1c2128"

    readonly property color contentSurface:            "#c9d1d9"
    readonly property color contentSurfaceVariant:     "#8b949e"
    readonly property color inverseSurface:            "#c9d1d9"
    readonly property color inverseContentSurface:     "#161b22"

    readonly property color primary:                   "#4da6ff"
    readonly property color contentPrimary:            "#0f1419"
    readonly property color primaryContainer:          "#30363d"
    readonly property color contentPrimaryContainer:   "#c9d1d9"
    readonly property color inversePrimary:            "#4da6ff"

    readonly property color secondary:                 "#39c5cf"
    readonly property color contentSecondary:          "#0f1419"
    readonly property color secondaryContainer:        "#30363d"
    readonly property color contentSecondaryContainer: "#c9d1d9"

    readonly property color tertiary:                  "#d29922"
    readonly property color contentTertiary:           "#0f1419"
    readonly property color tertiaryContainer:         "#30363d"
    readonly property color contentTertiaryContainer:  "#c9d1d9"

    readonly property color error:                     "#ff6b6b"
    readonly property color contentError:              "#0f1419"
    readonly property color errorContainer:            "#30363d"
    readonly property color contentErrorContainer:     "#c9d1d9"

    readonly property color outline:                   "#21262d"
    readonly property color outlineVariant:            "#1c2128"

    readonly property color shadow:                    "#000000"
    readonly property color scrim:                     "#000000"
}
