pragma Singleton
import QtQuick

// Generated by zen0x theme engine — edit zen0x/templates/quickshell-colors.qml.tpl
QtObject {
    readonly property color surface:                   "#2d353b"
    readonly property color surfaceDim:                "#2d353b"
    readonly property color surfaceBright:             "#4f585e"
    readonly property color surfaceContainerLowest:    "#2d353b"
    readonly property color surfaceContainerLow:       "#475258"
    readonly property color surfaceContainer:          "#475258"
    readonly property color surfaceContainerHigh:      "#4f585e"
    readonly property color surfaceContainerHighest:   "#56635f"

    readonly property color contentSurface:            "#d3c6aa"
    readonly property color contentSurfaceVariant:     "#d3c6aa"
    readonly property color inverseSurface:            "#d3c6aa"
    readonly property color inverseContentSurface:     "#475258"

    readonly property color primary:                   "#7fbbb3"
    readonly property color contentPrimary:            "#2d353b"
    readonly property color primaryContainer:          "#4f585e"
    readonly property color contentPrimaryContainer:   "#d3c6aa"
    readonly property color inversePrimary:            "#7fbbb3"

    readonly property color secondary:                 "#83c092"
    readonly property color contentSecondary:          "#2d353b"
    readonly property color secondaryContainer:        "#4f585e"
    readonly property color contentSecondaryContainer: "#d3c6aa"

    readonly property color tertiary:                  "#dbbc7f"
    readonly property color contentTertiary:           "#2d353b"
    readonly property color tertiaryContainer:         "#4f585e"
    readonly property color contentTertiaryContainer:  "#d3c6aa"

    readonly property color error:                     "#e67e80"
    readonly property color contentError:              "#2d353b"
    readonly property color errorContainer:            "#4f585e"
    readonly property color contentErrorContainer:     "#d3c6aa"

    readonly property color outline:                   "#606b6f"
    readonly property color outlineVariant:            "#56635f"

    readonly property color shadow:                    "#000000"
    readonly property color scrim:                     "#000000"
}
