windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
source = ~/.config/hypr/configs/apps.conf
source = ~/.config/hypr/apps/workspaces.conf
